cache: npm
language: node_js
node_js:
  - "node"
env:
  global:
    CC_TEST_REPORTER_ID=fb2e1d77435807872c42ae70439227cacc17ec9d5bf0bc5435cd1ba86bc8ad7c
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install                         # Install npm dependencies
script:
  - npm test                            # Frontend linting & specs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
